##
## EPITECH PROJECT, 2024
## zappy
## File description:
## Makefile
##

NAME 	= 	zappy_ai_our

RM		=	rm -rf

$(NAME):
		cp src/$(NAME) .
		chmod +x $(NAME)

all:	$(NAME)

clean:
		@$(RM) $(NAME)

fclean:	clean

re:		fclean all

.PHONY:	all clean fclean re
