##
## EPITECH PROJECT, 2022
## Makefile
## File description:
## Makefile
##

NAME = Z

SRC = Z.cpp

all:
	g++ -o $(NAME) $(SRC) -std=c++20 -Wall -Wextra -Werror -g3

clean:
	rm -f *.o
	rm -f *~

fclean : clean
	rm -f $(NAME)

re: fclean 	all
