##
## EPITECH PROJECT, 2022
## B-MUL-100-MAR-1-1-myhunter-angelo.anselmet
## File description:
## Makefile
##


all :
	make re -C ./antman
	make re -C ./giantman

clean :
		make clean -C ./antman
		make clean -C ./giantman

fclean :
		make fclean -C ./antman
		make fclean -C ./giantman

re : fclean all
