##
## EPITECH PROJECT, 2024
## Rush 1
## File description:
## Makefile
##

NAME = pushswap_checker

all : ${NAME}

${NAME}:
	ghc main.hs command.hs swap.hs -o $(NAME)

clean:
		rm -f *.hi
		rm -f *.o
		rm -f $(NAME)

fclean: clean

re: fclean all