##
## EPITECH PROJECT, 2022
## B-MUL-100-MAR-1-1-corewar-angelo.anselmet
## File description:
## Makefile
##

COREWAR = corewar

ASM = asm

all :
	make -C ./corewar
	make -C ./asm

clean :
		make clean -C ./corewar
		make clean -C ./asm

fclean :
		make fclean -C ./corewar
		make fclean -C ./asm

re :
	make re -C ./corewar
	make re -C ./asm
