##
## EPITECH PROJECT, 2022
## 103cipher
## File description:
## Makefile
##

NAME	=	104intersection

SRC	=		104intersection.py \

all:	$(NAME)

$(NAME):
		cp $(SRC) $(NAME)
		chmod 777 $(NAME)

clean:
		rm -f *.o

fclean:
		rm -f $(NAME)

re: fclean all
