##
## EPITECH PROJECT, 2022
## Makefile
## File description:
## Makefile
##

NAME = z

SRC = z.c

all:
	gcc -o $(NAME) $(SRC) -std=gnu17 -Wall -Wextra -g3

clean:
	rm -f *.o
	rm -f *~

fclean : clean
	rm -f $(NAME)

re: fclean 	all
