#!/usr/bin/env python3

import argparse
import sys
from AIWithRef.src.states import DisconnectedState
from AIWithRef.src.ai import ZappyAI


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Zappy AI", add_help=False)
    parser.add_argument("-p", type=int, help="Port number")
    parser.add_argument("-n", type=str, help="Team name")
    parser.add_argument("-h", type=str, default="localhost", help="Host name")
    parser.add_argument("-help", action="store_true", help="Display usage")
    try:
        args: argparse.Namespace = parser.parse_args()
        if args.help or not all([args.p, args.n]):
            raise SystemExit
    except SystemExit:
        print("USAGE: ./zappy_ai -p port -n name -h machine")
        sys.exit(0)
    sys.setrecursionlimit(100000)
    ai = ZappyAI(DisconnectedState())
    ai.connect(args.h, args.p, args.n)
